import React, { useEffect, useState } from 'react';
import { db, handleFirestoreError, OperationType } from '../firebase';
import { collection, query, orderBy, onSnapshot, addDoc, serverTimestamp, where, doc, getDoc } from 'firebase/firestore';
import { 
  UserCog, 
  Search, 
  Plus, 
  UserPlus, 
  X, 
  Loader2,
  Filter,
  Shield,
  Mail,
  Phone,
  Clock,
  CheckCircle2,
  AlertCircle
} from 'lucide-react';
import { UserProfile, UserRole, Attendance } from '../types';
import { format } from 'date-fns';
import { cn } from '../lib/utils';
import { useAuth } from '../context/AuthContext';

const Staff: React.FC = () => {
  const { profile } = useAuth();
  const [staff, setStaff] = useState<UserProfile[]>([]);
  const [attendance, setAttendance] = useState<Attendance[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [activeTab, setActiveTab] = useState<'list' | 'attendance'>('list');

  // Form state for new staff (Note: In a real app, this would also trigger Firebase Auth user creation)
  const [formData, setFormData] = useState({
    uid: '', // This would be generated by Firebase Auth
    email: '',
    displayName: '',
    role: 'nurse' as UserRole,
    status: 'active' as 'active' | 'inactive',
    phoneNumber: ''
  });

  useEffect(() => {
    if (!profile?.clinicId) {
      if (profile) setLoading(false);
      return;
    }

    const clinicId = profile.clinicId;

    const staffUnsub = onSnapshot(
      query(collection(db, 'users'), where('clinicId', '==', clinicId), orderBy('createdAt', 'desc')), 
      (snapshot) => {
        setStaff(snapshot.docs.map(doc => ({ ...doc.data() } as UserProfile)));
        setLoading(false);
      },
      (err) => {
        handleFirestoreError(err, OperationType.LIST, 'users');
        setLoading(false);
      }
    );

    const attendanceUnsub = onSnapshot(
      query(collection(db, 'attendance'), where('clinicId', '==', clinicId), orderBy('date', 'desc')), 
      (snapshot) => {
        setAttendance(snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as Attendance)));
      },
      (err) => {
        handleFirestoreError(err, OperationType.LIST, 'attendance');
      }
    );

    return () => {
      staffUnsub();
      attendanceUnsub();
    };
  }, [profile?.clinicId]);

  const filteredStaff = staff.filter(s => 
    s.displayName?.toLowerCase().includes(searchTerm.toLowerCase()) ||
    s.email.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!profile) return;
    setSubmitting(true);
    try {
      const clinicId = profile.clinicId;
      // In this demo, we're just adding to Firestore. 
      // In production, you'd call a cloud function or use Firebase Admin to create the Auth user.
      await addDoc(collection(db, 'users'), {
        ...formData,
        clinicId,
        createdAt: serverTimestamp()
      });

      // Audit Log
      await addDoc(collection(db, 'audit_logs'), {
        userId: profile.uid,
        userEmail: profile.email,
        action: 'ADD_STAFF_PROFILE',
        module: 'Staff Management',
        details: `Added staff profile for ${formData.displayName}`,
        timestamp: serverTimestamp(),
        clinicId
      });

      setIsModalOpen(false);
      setFormData({
        uid: '',
        email: '',
        displayName: '',
        role: 'nurse',
        status: 'active',
        phoneNumber: ''
      });
    } catch (error) {
      console.error('Error adding staff:', error);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Staff Management</h1>
          <p className="text-gray-500 mt-1">Manage clinic staff, roles, and attendance.</p>
        </div>
        <button
          onClick={() => setIsModalOpen(true)}
          className="inline-flex items-center justify-center gap-2 px-4 py-2.5 bg-blue-600 text-white rounded-xl font-semibold hover:bg-blue-700 transition-all shadow-sm"
        >
          <UserPlus className="w-5 h-5" />
          Add Staff Member
        </button>
      </div>

      {/* Tabs */}
      <div className="flex border-b border-gray-200">
        <button
          onClick={() => setActiveTab('list')}
          className={cn(
            "px-6 py-3 text-sm font-medium transition-all border-b-2",
            activeTab === 'list' ? "border-blue-600 text-blue-600" : "border-transparent text-gray-500 hover:text-gray-700"
          )}
        >
          Staff List
        </button>
        <button
          onClick={() => setActiveTab('attendance')}
          className={cn(
            "px-6 py-3 text-sm font-medium transition-all border-b-2",
            activeTab === 'attendance' ? "border-blue-600 text-blue-600" : "border-transparent text-gray-500 hover:text-gray-700"
          )}
        >
          Attendance Log
        </button>
      </div>

      {activeTab === 'list' && (
        <>
          {/* Search */}
          <div className="bg-white p-4 rounded-2xl shadow-sm border border-gray-100 flex flex-col sm:flex-row gap-4">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
              <input
                type="text"
                placeholder="Search by name or email..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full pl-10 pr-4 py-2 bg-gray-50 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all"
              />
            </div>
            <button className="inline-flex items-center justify-center gap-2 px-4 py-2 bg-white border border-gray-200 rounded-xl text-sm font-medium text-gray-600 hover:bg-gray-50 transition-all">
              <Filter className="w-4 h-4" />
              Filters
            </button>
          </div>

          {/* Staff Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {loading ? (
              <div className="col-span-full p-12 flex justify-center">
                <Loader2 className="w-8 h-8 text-blue-600 animate-spin" />
              </div>
            ) : filteredStaff.length > 0 ? (
              filteredStaff.map((member) => (
                <div key={member.uid} className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 hover:shadow-md transition-all group">
                  <div className="flex items-start justify-between mb-4">
                    <div className="w-12 h-12 rounded-full bg-blue-100 flex items-center justify-center text-blue-700 font-bold text-lg">
                      {member.displayName?.charAt(0) || member.fullName?.charAt(0) || member.email?.charAt(0) || '?'}
                    </div>
                    <span className={cn(
                      "px-2 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider",
                      member.status === 'active' ? "bg-green-100 text-green-700" : "bg-red-100 text-red-700"
                    )}>
                      {member.status}
                    </span>
                  </div>
                  <h3 className="text-lg font-bold text-gray-900">{member.displayName || 'Unnamed Staff'}</h3>
                  <p className="text-sm font-medium text-blue-600 capitalize mb-4 flex items-center gap-1.5">
                    <Shield className="w-3.5 h-3.5" />
                    {member.role}
                  </p>
                  
                  <div className="space-y-2 pt-4 border-t border-gray-50">
                    <div className="flex items-center gap-2.5 text-xs text-gray-500">
                      <Mail className="w-3.5 h-3.5" />
                      {member.email}
                    </div>
                    {member.phoneNumber && (
                      <div className="flex items-center gap-2.5 text-xs text-gray-500">
                        <Phone className="w-3.5 h-3.5" />
                        {member.phoneNumber}
                      </div>
                    )}
                  </div>
                </div>
              ))
            ) : (
              <div className="col-span-full p-12 text-center text-gray-500">
                <UserCog className="w-12 h-12 mx-auto mb-4 opacity-20" />
                <p>No staff members found.</p>
              </div>
            )}
          </div>
        </>
      )}

      {activeTab === 'attendance' && (
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
          {attendance.length > 0 ? (
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="bg-gray-50 border-b border-gray-100">
                    <th className="px-6 py-4 text-xs font-bold text-gray-500 uppercase tracking-wider">Staff Member</th>
                    <th className="px-6 py-4 text-xs font-bold text-gray-500 uppercase tracking-wider">Date</th>
                    <th className="px-6 py-4 text-xs font-bold text-gray-500 uppercase tracking-wider">Clock In</th>
                    <th className="px-6 py-4 text-xs font-bold text-gray-500 uppercase tracking-wider">Clock Out</th>
                    <th className="px-6 py-4 text-xs font-bold text-gray-500 uppercase tracking-wider text-right">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {attendance.map((log) => {
                    const member = staff.find(s => s.uid === log.uid);
                    return (
                      <tr key={log.id} className="hover:bg-gray-50 transition-colors">
                        <td className="px-6 py-4">
                          <p className="text-sm font-semibold text-gray-900">{member?.displayName || 'Unknown'}</p>
                          <p className="text-xs text-gray-500 capitalize">{member?.role}</p>
                        </td>
                        <td className="px-6 py-4">
                          <p className="text-sm text-gray-600">
                            {(() => {
                              try {
                                if (!log.date) return '-';
                                const date = (log.date as any).toDate ? (log.date as any).toDate() : new Date(log.date);
                                return isNaN(date.getTime()) ? '-' : format(date, 'PP');
                              } catch (e) { return '-'; }
                            })()}
                          </p>
                        </td>
                        <td className="px-6 py-4">
                          <p className="text-sm text-gray-600">
                            {(() => {
                              try {
                                if (!log.clockIn) return '-';
                                const date = (log.clockIn as any).toDate ? (log.clockIn as any).toDate() : new Date(log.clockIn);
                                return isNaN(date.getTime()) ? '-' : format(date, 'p');
                              } catch (e) { return '-'; }
                            })()}
                          </p>
                        </td>
                        <td className="px-6 py-4">
                          <p className="text-sm text-gray-600">
                            {(() => {
                              try {
                                if (!log.clockOut) return '-';
                                const date = (log.clockOut as any).toDate ? (log.clockOut as any).toDate() : new Date(log.clockOut);
                                return isNaN(date.getTime()) ? '-' : format(date, 'p');
                              } catch (e) { return '-'; }
                            })()}
                          </p>
                        </td>
                        <td className="px-6 py-4 text-right">
                          <span className={cn(
                            "px-2 py-0.5 rounded-full text-[10px] font-bold uppercase",
                            log.clockOut ? "bg-green-100 text-green-700" : "bg-amber-100 text-amber-700"
                          )}>
                            {log.clockOut ? 'Completed' : 'On Shift'}
                          </span>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          ) : (
            <div className="p-12 text-center text-gray-500">
              <Clock className="w-12 h-12 mx-auto mb-4 opacity-20" />
              <p>No attendance records found.</p>
            </div>
          )}
        </div>
      )}

      {/* Add Staff Modal */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6">
          <div className="absolute inset-0 bg-black/50 backdrop-blur-sm" onClick={() => setIsModalOpen(false)} />
          <div className="relative bg-white w-full max-w-lg rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
            <div className="p-6 border-b border-gray-100 flex items-center justify-between bg-white sticky top-0 z-10">
              <h2 className="text-xl font-bold text-gray-900">Add Staff Member</h2>
              <button onClick={() => setIsModalOpen(false)} className="p-2 text-gray-400 hover:text-gray-600 rounded-lg hover:bg-gray-100 transition-all">
                <X className="w-6 h-6" />
              </button>
            </div>
            
            <form onSubmit={handleSubmit} className="p-6 overflow-y-auto space-y-6">
              <div className="bg-amber-50 border-l-4 border-amber-400 p-4 rounded-md flex items-start gap-3">
                <AlertCircle className="w-5 h-5 text-amber-400 flex-shrink-0 mt-0.5" />
                <p className="text-xs text-amber-700">
                  Note: This form only creates the Firestore profile. In a production environment, 
                  you would also need to create a Firebase Auth account for the user.
                </p>
              </div>

              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Full Name *</label>
                  <input
                    required
                    type="text"
                    value={formData.displayName}
                    onChange={(e) => setFormData({...formData, displayName: e.target.value})}
                    className="w-full px-4 py-2 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:outline-none"
                    placeholder="Dr. Jane Smith"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Email Address *</label>
                  <input
                    required
                    type="email"
                    value={formData.email}
                    onChange={(e) => setFormData({...formData, email: e.target.value})}
                    className="w-full px-4 py-2 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:outline-none"
                    placeholder="jane@afyaclinic.com"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Role *</label>
                  <select
                    required
                    value={formData.role}
                    onChange={(e) => setFormData({...formData, role: e.target.value as any})}
                    className="w-full px-4 py-2 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:outline-none bg-white"
                  >
                    <option value="doctor">Doctor</option>
                    <option value="nurse">Nurse</option>
                    <option value="receptionist">Receptionist</option>
                    <option value="pharmacist">Pharmacist</option>
                    <option value="accountant">Accountant</option>
                    <option value="admin">Admin</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Phone Number</label>
                  <input
                    type="tel"
                    value={formData.phoneNumber}
                    onChange={(e) => setFormData({...formData, phoneNumber: e.target.value})}
                    className="w-full px-4 py-2 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:outline-none"
                    placeholder="0712 345 678"
                  />
                </div>
              </div>

              <div className="pt-4 flex gap-3 sticky bottom-0 bg-white">
                <button
                  type="button"
                  onClick={() => setIsModalOpen(false)}
                  className="flex-1 px-4 py-2.5 border border-gray-200 text-gray-600 rounded-xl font-semibold hover:bg-gray-50 transition-all"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={submitting}
                  className="flex-1 px-4 py-2.5 bg-blue-600 text-white rounded-xl font-semibold hover:bg-blue-700 transition-all shadow-sm disabled:opacity-50 flex items-center justify-center"
                >
                  {submitting ? <Loader2 className="w-5 h-5 animate-spin" /> : 'Create Profile'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default Staff;
